### ISSUE TITLE
Create new Data in Airtable Lookup,Linked Feilds?

### ISSUE THREAD

**Issue by ahsanislam007** [Sybit-Education/airtable.java#23]
There is an error when i try to create any record in a table where the field is attached to another table's record or the table have a lookup field it wont work it gives error 
![capture](https://user-images.githubusercontent.com/31167538/29586339-c9d9477e-87a3-11e7-8301-be5713ecbf12.PNG)

**Comment by Zelle97** [comment]
Hello,
I think the Error is connected with the record you want to create. The Object has to be exactly how it is described in your personal API from Airtable under create Table. If you provide me with Information how your Table and your record looks like I can help you there.

Greetings,
Zelle

**Comment by ahsanislam007** [comment]
I can send you my airtable detail 
Hansenkasper@gmail.com
Kasper123
In my aitable there is a table  sessions i want to insert the data into that table but problem is the field is an reference of another table i hope you can help me out.


And please insert sample data because the data already in it is in use please dont change it

**Comment by Zelle97** [comment]
Hey,
sorry but i am not sure why u left that E-mail there?

Can you show me how the Object you want to add to the Table "sessions" looks like?
If one field is a reference to another Table, that Field has to be an Array with the id of the referenced Data.

Greetings,
Zelle

**Comment by ahsanislam007** [comment]
Yes thats why i left that email and pasword will you please give me a test
file which can send data to the sessions table

On Sep 7, 2017 9:48 PM, "Zelle97" <notifications@github.com> wrote:

Hey,
sorry but i am not sure why u left that E-mail there?

Can you show me how the Object you want to add to the Table "sessions"
looks like?
If one field is a reference to another Table, that Field has to be an Array
with the id of the referenced Data.

Greetings,
Zelle

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Sybit-Education/airtable.java/issues/23#issuecomment-327858134>,
or mute the thread

**Comment by Zelle97** [comment]
Im closing this issue. Its a specific Problem not related to the api.
I contacted you via E-mail to provide you with more specific information about your Problem.
