### ISSUE TITLE
Release in Maven

### ISSUE THREAD

**Issue by Boblebol** [Sybit-Education/airtable.java#41]
Hello 

Could you deploy 0.2.2 version in maven repository

Thank you

**Comment by danielpsf** [comment]
+1

**Comment by zanedb** [comment]
+1

**Comment by jhult** [comment]
I've found [JitPack](https://jitpack.io/) to be helpful in scenarios where a release isn't published to a Maven repository:

- https://jitpack.io/#Sybit-Education/airtable.java/0.2.2
- https://jitpack.io/com/github/Sybit-Education/airtable.java/0.2.2/build.log

**Comment by stritti** [comment]
releases could be found on GitHub.
