### ISSUE TITLE
Table warns about using @SerializedName even if you already are using it

### ISSUE THREAD

**Issue by fstuff** [Sybit-Education/airtable.java#43]
Table does not really use any logic when deciding whether or not to throw a warning re. the need to use the SerializedName annotation.
Excerpt from Table.java:
```
  if (key.contains(" ") || key.contains("-")) {
            LOG.warn("Annotate columns having special characters by using @SerializedName for property: [" + key + "]");
```
The result is that every time there is a select operation this warning is generated.  It cruds up logs and is therefore annoying.  However, it appears not to break anything.

The solution would be to check from the presence of the SerializedName annotation, and only throw the warning if it is not present.

**Comment by HamzaAburaneh** [comment]
Can you tell me how you solved this issue?

**Comment by fstuff** [comment]
Hi, I don't think I did. :-)

However you could modify the Table.java class to use reflection to check for the SerializedName annotation as I indicate above.  Maybe someone at sybit will make a patch to fix the issue.

**Comment by stritti** [comment]
Probably you could provide a PR, @fstuff ?

**Comment by fstuff** [comment]
@stritti , having considered the code in question for a time, I think it should just be removed. 

The function has to do with mapping Airtable column names to Java class fields.  The Sybit Airtable.java library uses reflection to map airtable column names to java fields of the Table class with identical names as the column.  I have determined that the warning exists because the Airtable API supports column names with virtually no limitations, while [java field names](https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-3.8) are limited to what are called "java digits" and "java letters".  For example, airtable column names can have whitespace and special characters such as $%^ but java field names cannot contain whitespace or most special characters.  Additionally there are many java keywords that are reserved and cannot be used as the names of fields.

The Sybit Airtable.java library provides a solution where an airtable column name contains illegal characters--you can use the @@SerializedName annotation to associate a java field with an airtable column name that has illegal characters.

The warning that is the subject of my original post seems to be a half-hearted attempt to provide a warning where the supplied airtable column name contains characters that are illegal in java field names.  But it only checks for whitespace (' ') and hyphen ('-').  It does not check for any of the other restrictions on java field names, nor does it check to see if the supplied key is a reserved java keyword.  Therefore the way the function is written it will fail to catch many situations where a specified airtable column name contains characters that are illegal in java field names.  Additionally, as indicated in my original post the code currently does not even check to see whether the SerializedName annotation is being used or not.  Where the annotation is being used, there is no problem and therefore should be no warning.

In order to give proper coverage and generate a warning 100% of the time that we have an airtable column name that contains illegal characters for java fields, the check would have to be rewritten to check for all invalid characters and keywords.  I am not sure that the overhead of doing so is worth it. 

In consideration of this, I think it would be better to simply remove the warning and document the limitations mentioned above as part of the Table class documentation.

If you are agreeable to this I can of course submit a PR, but it would simply consist of deleting the few lines of code that log the warning.

**Comment by fstuff** [comment]
PR submitted

**Comment by stritti** [comment]
Thank you very much for your improvement of the library.
